version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: crisis-img
    container_name: crisis-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8090:80
    networks:
      - crisis-network
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: crisis-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: crisis-news
      MYSQL_USER: "crisisb15"
      MYSQL_PASSWORD: "Groundbeef404"
      MYSQL_ROOT_PASSWORD: "Groundbeef404"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./conf/mysql:/docker-entrypoint-initdb.d
    networks:
      - crisis-network
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8091:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - crisis-network
networks:
  crisis-network:
    driver: bridge